source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1.2"

gem "bootsnap", require: false
gem "image_processing", "~> 1.2"
gem "importmap-rails"
gem "inline_svg"
gem "jbuilder"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"
gem "sprockets-rails"
gem "standard"
gem "stimulus-rails"
gem "tailwindcss-rails"
gem "turbo-rails"
gem "tzinfo-data", platforms: %i[windows jruby]

group :development, :test do
  gem "pry-rails"
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
end

gem "dockerfile-rails", ">= 1.5", :group => :development

gem "sentry-ruby", "~> 5.15"

gem "sentry-rails", "~> 5.15"
